matrix:
    include:
        - language: node_js
          node_js:
              - '12'
          cache: 
              - yarn: true
          before_install:
              - cd frontend
          install:
              - yarn install
          script:
              - ./node_modules/.bin/eslint src
              - yarn test --coverage --watchAll=false
        
        - language: python
          python:
              - '3.7'
          before_install:
              - cd backend/adoorback
          install:
              - pip install -r requirements.txt
          script:              
              - pylint --load-plugins pylint_django */models.py */views/*.py */tests/*.py
              - python manage.py makemigrations
              - python manage.py migrate --run-syncdb
              - coverage run --omit='manage.py','./adoorback/*.py','./*/tests.py' --source='.' manage.py test
              - coverage run --branch --omit='manage.py','./adoorback/*.py','./*/tests.py' --source='.' manage.py test
              - coverage xml