matrix:
  include:
  - language: node_js
    node_js:
    - '12'
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "Gwa4HKVSn8NpUV1ESrdX9rCfSQ186645H9ry3Q7rI4Ej8BTl0olVYeY/d4Rd5XaIBXc9Nyvgf5WjMr9CzM3jdwpKsfxLQzvQfzffqRkLxKfKuN+6KNcdujMZEOlU23gM+xpfDghpE5EscCvtn8/gtYl/HMs18v5tbYmmScbqxPIZ6NHDQz85KZcXqmL2JYQQK30n/KiiuEVpEJNr9LOxuZ0e/SwlQcAtKwkfCSN304oIB8UN3R0wp9tqYLPzWHSLrth3ivE+11tu3nmhCHaQsLEVwIS8T/jgcofmsrt3dv1+EoiFeoFeVTy5oBt6/vkOy6pDfr3HlpzvZE6zbcHw67kWR3l+7aPZmFnc4EeD3MJas55i08fXi+WQJOHWgBp7sKJaDqO8ZJMFsdxE60lI5b+3TUW975JKKA0hcdHbzXYmBq1nMghhmREamI01FRF7xWV0m0nYpIenGmNFBPqRcIpIgXJtnSNt/KUA/K+0ioglNBXA0UlJwyhUsnn8ORmYlsWdeeIBoU+WiDtqBcpkBpujTlP0YjWTOYLfIz55VlogNn5PWeryyrgai1CnExPiWlVgaMPWQQ8ZcJD2VmkfkhUa6sPS6+/qSoFVjyoYBjyfLctTTw3oOmdZ0a7BmJR+3MEGQ2rILUOe4LBJxEkfy3CjYRAxr/BfCqfBUeTfh9I="
    cache:
    - yarn: true
    before_install:
    - cd frontend
    install:
    - yarn install
    ignore:
    - ./src/serviceWorker.js
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - cd .. && sonar-scanner
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - language: python
    python:
    - '3.7'
    before_install:
    - cd backend/adoorback
    install:
    - pip install -r requirements.txt
    script:
    - coverage run --branch --omit='manage.py','./adoorback/*.py','./*/tests.py' --source='.' manage.py test
    - coverage report -m
    - coverage xml
    - cd ../.. && sonar-scanner
    after_success:
    - coveralls
