matrix:
  include:
  - language: node_js
    node_js:
    - '12'
    addons:
      sonarcloud:
        organization: swsnu
        token:
          secure: UyibO0r9M3SbXOoBoBf0GNk6t/a6Tntje0JwEZoQpqLxzclf98bt4P5yJBN7+cKQfYWi/SQPLV9Dwwn3fnvtAfRofTqYzZAK8s4OgGsAta8aJvpUu4qlmvpznctSqCFkOL8A7zeVVBxqvSQ004RbZ2OHbRdIfTF5UQmtaNanW7IIGSo4dmqo2n35iuNTLYkNO1yjuEYgr67fWAPNk7RzUJOVi6Qe6xIjuuPCrdvX4UbXpRmmK6dXXn8qNmqk/QN5RmLSBcxqDMK7Qq8gGNkwI0DWu0dkpQFiQAUlAnkdTn1/NIi1caknRN3QD/Hc8kwdGleBPckpTWu1RMp2eF+TDCrOa6x9qIrGp5vA6MRE7QVo3O5g536e+Lggvv9gg105YpWD55LYNz5l+IH6c/A8dounsIzNW/eorsds1iFIuERmdHXKOCBiHBhAylCZw5EPi872qQSzor32RaKyPQcfJzqz/vgUrTPFgJbBGm1ic+3gtcTskoNQ1E8EW3JqJuInxH++K8YPaVxH6gGK09rG93odTD6fblr0QyhWBHJfTKuilOjoXP66MAEgmXCPSTji3bPYtXUa/5hiM1XfVad7ekpTqZgrMMEqEP4mAI77NI03V3qEbVYeYAtmVIF3wCykNbBJi4C+7kVyW/C4t8EXrW8wS8tclujZZ+/XliDP53g=
    cache:
    - yarn: true
    before_install:
    - cd frontend
    install:
    - yarn install
    ignore:
    - "./src/serviceWorker.js"
    script:
    - "./node_modules/.bin/eslint src"
    - yarn test --coverage --watchAll=false
    - cd .. && sonar-scanner
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - language: python
    python:
    - '3.7'
    cache:
    - pip: true
    before_install:
    - cd backend/adoorback
    install:
    - pip install -r requirements.txt
    script:
    - python manage.py makemigrations account feed comment like
    - python manage.py migrate
    - coverage run --omit='manage.py','./adoorback/*.py','./*/tests.py','./*/urls.py','./*/views.py'
      --source='.' manage.py test
    - coverage run --branch --omit='manage.py','./adoorback/*.py','./*/tests.py','./*/urls.py','./*/views.py'
      --source='.' manage.py test
    - coverage xml
    after_success:
    - coveralls
    after_script:
    - cd ..
env:
  global:
    secure: IwHNYPEkJgvHK0mtRe+8tiFbKOMbrXg3WetdsF/ZXe3UQnCFcQfyvqII6NccE9L7fRfwKChBH0K8SM7IubfFq9/MRVFqHNO/nQKc+ZJHL+ngpMEKamC2DllHSXKdLkimnv5YU3cOvkX+p4gPSam1QS8CUyc27mIWV/9lxO6+wYJIlFZN5c7WeJIyPpUjBlY3gDQpsGqXaj/HyJe4tibIpnJSDGYKDlWnT4u1PmGe3ZLYAyqDrTF9T+Mn7f7OVdigIL8BLgeU35YFDLh3KaZtIYwJe7LxNgdGf8b6FUEYuxaBch8f/ffWu0oqXMXHA/hBT5kfMongPRukmBD1Pf/NvqI/xeHO2uUqXiT7HSkcJbvAneKFsO7v42oJw2SjSaxauEighV/iFM1u4XH/1N/bmBPU7qx1QH+oNx99+P5IMBWGpMAaUKs8i5UXCSf/kCO9bKkX8CSTp1YX/NvECFFJOHcf0w1c7/8tJp8YQS79hMMxNaF4ZFRNDnCCkSabjlzSXtHgJEaAN1+Ue28pzYtQoRXjwpgt6g2his1Uc32UcdWUuoVvb241qOJIhYmXU2cCsAo9D+3LhzwU7/bHvB+gpJtXdOCgWmXbKuQx4yU7tcHAV4vQvSJzHgZB6DgSqL/cY95kzsLCIZzNJtcjbqUXLDMbVpxxf+3Qv7ObM83CY7w=
